### ISSUE TITLE
UserAgent failing in scraper

### ISSUE THREAD

**Issue by torgvad** [torgvad/Retailer-Assistant-Dev-Version#8]
The following occurs:

Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "C:\Users\vtorg\AppData\Local\Programs\Python\Python37\lib\site-packages\fake_useragent\utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "C:\Users\vtorg\AppData\Local\Programs\Python\Python37\lib\site-packages\fake_useragent\utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range

**Comment by torgvad** [comment]
The issue cannot be consistently recreated to test. The only code that invokes the useragent is in a try/except, which is located in a while True. This error is completely out of my hands, but I will continue to run the code in hopes of pinpointing this issue and at least fix it on my end.
